version: '3'
services:
  #Nginx Service
  webserver:
    image: nginx:1.17.7-alpine
    container_name: ${WEBSERVER_CONTAINER_NAME}
    restart: unless-stopped
    tty: true
    volumes:
      - ${LARAVEL_ROOT_PATH}:/var/www/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./logs/nginx/:/var/log/nginx/
      - ${SSL_PATH}:/certs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      SSL:
      SSLCERT: ${SSL_CERTIFICATE}
      SSLKEY: ${SSL_KEY}
    logging:
      driver: ${WEBSERVER_LOG_DRIVER:-json-file}
      options:
        max-size: ${WEBSERVER_LOG_MAX_SIZE:-2m}
        max-file: ${WEBSERVER_LOG_MAX_FILE:-10}

#Docker Networks
networks:
  default:
     external:
       name: ${NETWORK}
